#!/usr/bin/env bash
# scripts/release-assemble.sh
#
# Turns the per-image outputs of scripts/release-image.sh into the files a
# GitHub release carries, then checks the compose overlay against the stack.
# Writes, into OUT_DIR (default dist/release):
#
#   compose.release.yaml                overlay: every first-party service runs
#                                       its release image, pinned by digest
#   images.txt                          the same images, one reference per line
#   aikonos-<name>-<version>.cdx.json   CycloneDX SBOM, one per image
#   aikonos-<name>-<version>.spdx.json  SPDX SBOM, one per image
#   aikonos-<version>-source.tar.gz     the source tree the images were built from
#   SHA256SUMS                          checksums of every file above
#
# and release notes with this version's verification commands to NOTES_FILE
# (default dist/release-notes.md). Signing SHA256SUMS is left to the release
# workflow, which holds the signing identity; this script never signs.
#
# The overlay check renders compose.yaml + each variant overlay (local, azure,
# onprem) + the third-party digest pins + the new overlay, with every profile
# enabled, and fails if:
#   - the overlay names a service compose does not define (compose would
#     create it as a new, empty service), or
#   - a service outside the test-only `dev` profile would still be built from
#     source, i.e. a first-party image is missing from .github/release-images.json,
#   - or a service does not resolve to exactly the image the release pushed.
#
# Usage: VERSION=v1.2.3 IMAGE_PREFIX=ghcr.io/<owner>/aikonos scripts/release-assemble.sh
# Env:   IMAGES_DIR (dist/images), OUT_DIR (dist/release, must be absent or
#        empty), NOTES_FILE (dist/release-notes.md), SOURCE_REF (HEAD),
#        REPOSITORY (<owner>/<repo>, default $GITHUB_REPOSITORY).
# Needs git, jq and the docker compose CLI (no daemon).

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
cd "${REPO_ROOT}"

log() { printf '[release-assemble] %s\n' "$*"; }
die() { printf '[release-assemble] ERROR: %s\n' "$*" >&2; exit 1; }

: "${VERSION:?VERSION is required, e.g. v1.2.3}"
: "${IMAGE_PREFIX:?IMAGE_PREFIX is required, e.g. ghcr.io/<owner>/aikonos}"
IMAGES_DIR="${IMAGES_DIR:-dist/images}"
OUT_DIR="${OUT_DIR:-dist/release}"
NOTES_FILE="${NOTES_FILE:-dist/release-notes.md}"
SOURCE_REF="${SOURCE_REF:-HEAD}"
REPOSITORY="${REPOSITORY:-${GITHUB_REPOSITORY:-adamdekan/aikonos}}"

[[ "${VERSION}" =~ ^[A-Za-z0-9_][A-Za-z0-9_.-]{0,127}$ ]] || die "VERSION is not a valid image tag: ${VERSION}"
for tool in git jq docker; do
  command -v "${tool}" >/dev/null 2>&1 || die "${tool} not found on PATH"
done
if command -v sha256sum >/dev/null 2>&1; then
  SHA256=(sha256sum)
elif command -v shasum >/dev/null 2>&1; then
  SHA256=(shasum -a 256)
else
  die "neither sha256sum nor shasum found on PATH"
fi

[[ -d "${IMAGES_DIR}" ]] || die "image outputs not found: ${IMAGES_DIR}"
if [[ -e "${OUT_DIR}" ]] && [[ -n "$(ls -A "${OUT_DIR}")" ]]; then
  die "${OUT_DIR} is not empty; remove it first"
fi
mkdir -p "${OUT_DIR}" "$(dirname "${NOTES_FILE}")"

# ---------------------------------------------------------------------------
# Collect "<service> <name> <ref>" per image, validating each record.
# ---------------------------------------------------------------------------
ENTRIES=""
for ref_file in "${IMAGES_DIR}"/*.ref; do
  [[ -e "${ref_file}" ]] || die "no *.ref files in ${IMAGES_DIR}"
  name="$(basename "${ref_file}" .ref)"
  read -r service ref extra < "${ref_file}" || true
  [[ -z "${extra:-}" ]] || die "unexpected content in ${ref_file}"
  [[ "${service:-}" =~ ^[a-z0-9][a-z0-9_-]*$ ]] || die "bad service name in ${ref_file}: '${service:-}'"
  [[ "${ref:-}" == "${IMAGE_PREFIX}/${name}:${VERSION}@sha256:"* && "${ref}" =~ @sha256:[0-9a-f]{64}$ ]] \
    || die "${ref_file} is not ${IMAGE_PREFIX}/${name}:${VERSION}@sha256:<digest> (got: '${ref:-}')"
  for ext in cdx.json spdx.json; do
    [[ -s "${IMAGES_DIR}/${name}.${ext}" ]] || die "missing SBOM: ${IMAGES_DIR}/${name}.${ext}"
  done
  ENTRIES+="${service} ${name} ${ref}"$'\n'
done
ENTRIES="$(printf '%s' "${ENTRIES}" | LC_ALL=C sort)"

duplicates="$(printf '%s\n' "${ENTRIES}" | awk '{print $1}' | uniq -d)"
[[ -z "${duplicates}" ]] || die "more than one image for service(s): ${duplicates}"
log "$(printf '%s\n' "${ENTRIES}" | wc -l | tr -d ' ') images for ${VERSION}"

# ---------------------------------------------------------------------------
# Release files.
# ---------------------------------------------------------------------------
OVERLAY="${OUT_DIR}/compose.release.yaml"
{
  echo "# compose.release.yaml — Aikonos ${VERSION}"
  echo "#"
  echo "# Generated by scripts/release-assemble.sh. Do not edit it: SHA256SUMS covers it."
  echo "#"
  echo "# Runs every first-party service from its signed ${VERSION} release image instead"
  echo "# of building it from source. Layer it last, after the variant overlay and the"
  echo "# third-party digest pins, e.g.:"
  echo "#   docker compose -f compose.yaml -f deploy/compose/compose.onprem.yaml \\"
  echo "#     -f deploy/compose/compose.digests.yaml -f compose.release.yaml up -d"
  echo "#"
  echo "# Verify the release first: scripts/verify-release.sh ${VERSION}"
  echo "# (docs/14-signed-releases.md). To pull the same digests from a mirror, set"
  echo "# AIKONOS_IMAGE_PREFIX; a digest-preserving copy keeps the signatures valid."
  echo "services:"
  while read -r service name ref; do
    echo "  ${service}:"
    echo "    build: !reset null"
    echo "    image: \${AIKONOS_IMAGE_PREFIX:-${IMAGE_PREFIX}}${ref#"${IMAGE_PREFIX}"}"
  done <<< "${ENTRIES}"
} > "${OVERLAY}"

printf '%s\n' "${ENTRIES}" | awk '{print $3}' > "${OUT_DIR}/images.txt"

while read -r _ name _; do
  cp "${IMAGES_DIR}/${name}.cdx.json" "${OUT_DIR}/aikonos-${name}-${VERSION}.cdx.json"
  cp "${IMAGES_DIR}/${name}.spdx.json" "${OUT_DIR}/aikonos-${name}-${VERSION}.spdx.json"
done <<< "${ENTRIES}"

git archive --format=tar.gz --prefix="aikonos-${VERSION}/" \
  --output="${OUT_DIR}/aikonos-${VERSION}-source.tar.gz" "${SOURCE_REF}"

(
  cd "${OUT_DIR}"
  export LC_ALL=C
  for f in *; do
    [[ "${f}" == "SHA256SUMS" ]] && continue
    "${SHA256[@]}" -- "${f}"
  done > SHA256SUMS
)

# ---------------------------------------------------------------------------
# Overlay check against every compose variant.
# ---------------------------------------------------------------------------
WORKDIR="$(mktemp -d)"
trap 'rm -rf "${WORKDIR}"' EXIT

# Dummy env files, never the real .env (same convention as pin-image-digests.sh).
for variant in local azure onprem; do
  cp "deploy/compose/.env.${variant}.example" "${WORKDIR}/${variant}.env"
done

# compose_all_profiles <env file> <-f file args...> -- <compose subcommand...>
# Runs the subcommand with every profile the files define switched on, so a
# service behind any profile is checked. Listing the profiles is its own compose
# call; failing it must stop the check rather than let it run against the
# profile-less subset and pass vacuously. AIKONOS_IMAGE_PREFIX is unset on
# purpose: the check is of the default image references.
compose_all_profiles() {
  local env_file="$1" files=() profiles profile profile_args=()
  shift
  while [[ $# -gt 0 && "$1" != "--" ]]; do files+=("$1"); shift; done
  [[ "${1:-}" == "--" ]] || die "compose_all_profiles: missing -- before the subcommand"
  shift
  profiles="$(env -u AIKONOS_IMAGE_PREFIX docker compose --env-file "${env_file}" "${files[@]}" config --profiles)" \
    || die "could not list compose profiles for: ${files[*]}"
  [[ -n "${profiles}" ]] || die "no compose profiles found for: ${files[*]}"
  while read -r profile; do
    [[ -n "${profile}" ]] && profile_args+=(--profile "${profile}")
  done <<< "${profiles}"
  env -u AIKONOS_IMAGE_PREFIX docker compose --env-file "${env_file}" "${files[@]}" "${profile_args[@]}" "$@"
}

overlay_services="$(printf '%s\n' "${ENTRIES}" | awk '{print $1}' | LC_ALL=C sort)"
base_services="$(compose_all_profiles "${WORKDIR}/local.env" -f compose.yaml -- config --services)" \
  || die "could not list the services in compose.yaml"
base_services="$(printf '%s\n' "${base_services}" | LC_ALL=C sort)"
unknown="$(LC_ALL=C comm -13 <(printf '%s\n' "${base_services}") <(printf '%s\n' "${overlay_services}"))"
[[ -z "${unknown}" ]] || die "the overlay names service(s) compose.yaml does not define: ${unknown//$'\n'/ }"

# check_variant <variant> <compose file args between compose.yaml and the overlay>
check_variant() {
  local variant="$1"
  shift
  local rendered="${WORKDIR}/${variant}.json" still_built service name ref got
  compose_all_profiles "${WORKDIR}/${variant}.env" -f compose.yaml "$@" -f "${OVERLAY}" \
    -- config --format json > "${rendered}" || die "compose config failed for the ${variant} variant"

  still_built="$(jq -r '.services | to_entries[]
    | select(.value.build != null)
    | select((.value.profiles // []) != ["dev"])
    | .key' "${rendered}")"
  [[ -z "${still_built}" ]] \
    || die "${variant}: still built from source, no release image: ${still_built//$'\n'/ } (add it to .github/release-images.json)"

  while read -r service name ref; do
    got="$(jq -r --arg s "${service}" '.services[$s].image // empty' "${rendered}")"
    [[ "${got}" == "${ref}" ]] || die "${variant}: ${service} resolves to '${got}', expected '${ref}'"
  done <<< "${ENTRIES}"
  log "overlay OK for the ${variant} variant"
}

# The third-party digest pins are a prod-overlay companion (deploy/compose/README.md),
# so they are layered for azure and onprem only, as an operator would.
check_variant local
check_variant azure -f deploy/compose/compose.azure.yaml -f deploy/compose/compose.digests.yaml
check_variant onprem -f deploy/compose/compose.onprem.yaml -f deploy/compose/compose.digests.yaml

# ---------------------------------------------------------------------------
# Release notes: what was published and how to check it.
# ---------------------------------------------------------------------------
IDENTITY="https://github.com/${REPOSITORY}/.github/workflows/release.yml@refs/tags/${VERSION}"
{
  cat <<EOF
## Verify this release

Every image below is signed with [cosign](https://github.com/sigstore/cosign) by this
repository's release workflow (keyless, recorded in Sigstore's public transparency log),
and carries a signed CycloneDX SBOM attestation and SLSA build provenance. \`SHA256SUMS\`
covers every other file attached to this release and is signed the same way.

With cosign 3.x, in a directory holding this release's files:

\`\`\`bash
ID=${IDENTITY}
ISSUER=https://token.actions.githubusercontent.com
EOF
  # Quoted: the commands are printed for the reader to run, not expanded here.
  cat <<'EOF'

cosign verify-blob --bundle SHA256SUMS.sigstore.json \
  --certificate-identity "$ID" --certificate-oidc-issuer "$ISSUER" SHA256SUMS
sha256sum -c SHA256SUMS   # macOS: shasum -a 256 -c SHA256SUMS

while read -r image; do
  cosign verify --certificate-identity "$ID" --certificate-oidc-issuer "$ISSUER" "$image" >/dev/null
  cosign verify-attestation --type cyclonedx \
    --certificate-identity "$ID" --certificate-oidc-issuer "$ISSUER" "$image" >/dev/null
done < images.txt
```
EOF
  cat <<EOF

\`scripts/verify-release.sh ${VERSION}\` in the source tarball runs the same checks and
downloads the files for you. The full guide, including deploying from these images:
[docs/14-signed-releases.md](https://github.com/${REPOSITORY}/blob/${VERSION}/docs/14-signed-releases.md).

## Images

| Service | Image |
|---|---|
EOF
  while read -r service _ ref; do
    echo "| \`${service}\` | \`${ref}\` |"
  done <<< "${ENTRIES}"
} > "${NOTES_FILE}"

log "Wrote $(find "${OUT_DIR}" -type f | wc -l | tr -d ' ') files to ${OUT_DIR} and notes to ${NOTES_FILE}"
