-- 010_alerts.sql
-- Persistent history for security alerts fired by the alerting engine.
-- Rows are written async (fire-and-forget) by the Engine; never affect any gate.
-- alert_id is UUIDv7 (time-sortable) generated by internal/ids.EventID().
-- summary is free-form JSONB carrying rule-specific detail (title, detail, event_id).
-- RLS mirrors the other tables: rows visible/writable only for the session tenant.

CREATE TABLE IF NOT EXISTS alerts (
    alert_id   TEXT        PRIMARY KEY,
    tenant_id  UUID        NOT NULL,
    rule       TEXT        NOT NULL,
    severity   TEXT        NOT NULL,
    summary    JSONB       NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_alerts_tenant_created ON alerts (tenant_id, created_at DESC);

ALTER TABLE alerts ENABLE ROW LEVEL SECURITY;
CREATE POLICY alerts_tenant_isolation ON alerts
    USING (tenant_id::text = current_setting('app.current_tenant', true));

INSERT INTO schema_migrations (version, description)
VALUES ('010', 'alerts table for persistent security alert history')
ON CONFLICT (version) DO NOTHING;
